export const APPEND_INTEREST_LIST = 'moments/APPEND_INTEREST_LIST'
export const LOAD_INTEREST_LIST = 'moments/LOAD_INTEREST_LIST'
export const RESET_INTEREST_LIST = 'moments/RESET_INTEREST_LIST'
export const CHANGE_INTEREST_STATUS = 'moments/CHANGE_INTEREST_STATUS'

export const APPEND_INDUSTRY_LIST = 'moments/APPEND_INDUSTRY_LIST'
export const LOAD_INDUSTRY_LIST = 'moments/LOAD_INDUSTRY_LIST'
export const RESET_INDUSTRY_LIST = 'moments/RESET_INDUSTRY_LIST'
export const CHANGE_INDUSTRY_STATUS = 'moments/CHANGE_INDUSTRY_STATUS'


//detail

